### ISSUE TITLE
Package hdx-python-utilities for conda-forge

### ISSUE THREAD

**Issue by kynan** [OCHA-DAP/hdx-python-utilities#10]
This package is a dependency for [hdx-python-country](https://github.com/OCHA-DAP/hdx-python-country), see OCHA-DAP/hdx-python-country#14

/cc @turnerm

Dependencies:
* [x] ~basicauth~ (conda package: pr conda-forge/staged-recipes#21610)
  * [x] ~blocked: rdegges/python-basicauth#9)~
* [x] beautifulsoup4==4.11.2
* [x] email_validator==1.3.1
* [x] ~frictionless[excel,json]>=4.40.8~ (blocked: conda-forge/frictionless-feedstock#93)
* [x] frictionless==5.5.1
* [x] ijson>=3.0
* [x] jsonlines>=1.2
* [x] loguru
* [x] openpyxl>=3.0
* [x] python-dateutil==2.8.2
* [x] ratelimit
* [x] requests-file
* [x] ruamel.yaml
* [x] tableschema-to-template>=0.0.12 (conda package: conda-forge/staged-recipes#21936)
  * [x] blocked by hubmapconsortium/tableschema-to-template#28
  * [x] jsonschema>=1.0.0
  * [x] pyyaml>=3.13
  * [x] xlsxwriter>=1.2.8
* [x] xlrd>=1.2
* [x] xlwt>=1.2

**Comment by kynan** [comment]
This package depends on [basicauth](https://github.com/rdegges/python-basicauth), which is not currently packaged for conda-forge. Annoyingly, it has no source distribution (rdegges/python-basicauth#9) and thus cannot be packaged.

**Comment by mcarans** [comment]
If basicauth cannot be packaged, it should be possible to avoid its usage. It is only used in one place in the code:
https://github.com/OCHA-DAP/hdx-python-utilities/blob/main/src/hdx/utilities/session.py#L159

I think the session headers could be set directly with `s.headers["Authorization"] = basic_auth` but basic_auth would need to be checked to see if it starts with "Basic " and if not have that prepended. Also tests would need updating.

**Comment by turnerm** [comment]
@kynan what's your take on both of these blockers being resolved in the near future? 

It looks like basicauth hasn't seen a lot of activity in the last few years, so I'm wondering if our best bet is to remove it as Mike suggested.

**Comment by kynan** [comment]
Not too hopeful I have to admit. I've reached out to the basicauth author, but given the last change was in 2018 I'd consider this package abandoned.

For frictionless we can maybe unblock by just adding the "extra" dependencies directly.

**Comment by turnerm** [comment]
With #12 and #13 (Mike's review pending) I've addressed the two remaining dependencies, however, from the `frictionless` extras it looks to me that one of the new dependencies [`tableschema-to-template`](https://github.com/hubmapconsortium/tableschema-to-template) is not on conda-forge (or at least I can't find it)

**Comment by mcarans** [comment]
I've created 3.4.8 that no longer needs basicauth and has frictionless extras directly

**Comment by kynan** [comment]
Thanks @turnerm @mcarans. Indeed tableschema-to-template needs to be packaged and unfortunately this is currently blocked by hubmapconsortium/tableschema-to-template#28

**Comment by turnerm** [comment]
Looking into this a bit more today,  while `tableschema-to-template` has not been update for some time, the sole developer behind it is still very active. I'm assuming he's too busy to tackle it for now. 

This might be a terrible suggestion, but @mcarans what if we were to (temporarily) remove it? I checked and the only place it's used in `frictionless` is [here](https://github.com/frictionlessdata/framework/blob/main/frictionless/formats/excel/mapper.py#L13-L15), i.e. in the method `write_schema`, which is not anywhere used in `hdx-python-utilities` nor in the rest of the `frictionless` codebase. For me the tests work without it. What do you think?

**Comment by mcarans** [comment]
@turnerm I've pinged the developer about the PR Florian made, but if that doesn't elicit a response, sure we can do that.

**Comment by roll** [comment]
Hi, sorry for the late response but it seems optional dependencies are not supported on Conda - https://github.com/conda/conda/issues/7502

I think it might be problematic to guess the exact set of optional dependencies needed for a release like `frictionless-with-formats` (or etc) as it depends on the usage. WDYT of specifying the dependencies in your package directly as it might be the most effective way? For example, the already mentioned missing `tableschema-to-template` will never fail unless the client runs the export method that uses it

**Comment by kynan** [comment]
@roll thanks for investigating! Specifying the extra dependencies directly is what I've done, so this isn't a blocker.

**Comment by mcarans** [comment]
I've merged the PR to remove the tableschema requirement.

**Comment by kynan** [comment]
@mcarans I need an sdist on PyPI to package this for conda 🙃 Can you please upload the sdist for 3.5.3 ?

**Comment by mcarans** [comment]
@kynan I have added an sdist for 3.5.4

**Comment by kynan** [comment]
@mcarans Thanks, I can see that 3.5.4 has an sdist :)

However I noticed that frictionless[excel] has a dependency on tableschema-to-template, so we're unfortunately still blocked on hubmapconsortium/tableschema-to-template#28

**Comment by mcarans** [comment]
@kynan Did you mean frictionless[excel] in the requirements.txt? I had already commented out tableschema-to-template in setup.cfg. 

Now that 0.0.13 has been released with the license file, I guess it's ok to put tableschema-to-template back in setup.cfg like this `tableschema-to-template>=0.0.13`?

**Comment by kynan** [comment]
Finally, all dependencies are available 🎉  Sent conda-forge/staged-recipes#21978

**Comment by kynan** [comment]
And done! [Package is live](https://anaconda.org/conda-forge/hdx-python-utilities) @mcarans @turnerm
